import { type BindConfig, type BindNodeEntry } from "./BindJsonManager.ts";
import { type ParsedPrefab } from "../parsers/PrefabParser.ts";
import { lookupComponentType } from "../parsers/ComponentTypeMap.ts";

export interface GenerateOptions {
  /** 工具版本号（写入文件头部注释） */
  toolVersion?: string;
  /** 额外提示要不要把根节点也算上（影响节点路径解析方式） */
  emitRuntimeAssertions?: boolean;
}

/**
 * 把 BindConfig + ParsedPrefab 渲染为 PrefabView 的 .gen.ts 代码。
 *
 * 生成的代码原则：
 * - 文件顶部带「禁止手改」标记；
 * - 一个继承自 cc.Component 的 PrefabView 类；
 * - `bind(root: Node)` 方法：传入运行时 prefab 实例化后的根 Node，
 *   按 path 遍历 children 取出节点和组件并写到 readonly 字段；
 * - 每个 path 都做防御性检查（DEV 下 `assert`）；
 * - 字段全部使用 `readonly`，绑定阶段通过 `(this as any)` 写入。
 *
 * 不做任何运行时反射或字符串拼接 path：路径在生成时就硬编码到代码里。
 */
export function generateGenTs(
  config: BindConfig,
  parsed: ParsedPrefab,
  opts: GenerateOptions = {}
): string {
  const lines: string[] = [];
  const importsFromCc = new Set<string>(["Component", "Node", "_decorator"]);
  const importsFromSp = new Set<string>();

  // 收集所有要 import 的类型
  for (const entry of config.nodes) {
    for (const comp of entry.components ?? []) {
      const info = lookupComponentType(comp.rawType);
      if (!info) continue;
      if (info.importFrom === "cc") {
        // info.tsName 形如 "animation.AnimationController" 时，import 顶层名
        const top = info.tsName.split(".")[0];
        importsFromCc.add(top);
      } else if (info.importFrom === "sp") {
        importsFromSp.add("sp");
      }
    }
  }

  // -------- 文件头 --------
  lines.push(
    "// =====================================================================",
    "//  THIS FILE IS AUTO-GENERATED BY genbot. DO NOT EDIT BY HAND.",
    "//",
    `//  source prefab : ${config.prefab}`,
    `//  bind config   : ${config.prefab.replace(/\.prefab$/, ".bind.json")}`,
    `//  generated at  : ${new Date().toISOString()}`,
    `//  tool version  : ${opts.toolVersion ?? "0.1.0"}`,
    "//",
    "//  To change exposed nodes/components, edit the .bind.json file or use",
    "//  the genbot editor panel, then re-run genbot.",
    "// =====================================================================",
    ""
  );

  // -------- imports --------
  const ccList = Array.from(importsFromCc).sort();
  lines.push(`import { ${ccList.join(", ")} } from "cc";`);
  if (importsFromSp.size > 0) {
    lines.push(`import { sp } from "cc";`);
  }
  lines.push("");

  // -------- 节点路径常量（便于 debug） --------
  lines.push("/** 该 PrefabView 绑定的所有节点路径（相对根节点） */");
  lines.push("export const NODE_PATHS = {");
  for (const entry of config.nodes) {
    lines.push(`  ${entry.field}: ${JSON.stringify(entry.path)},`);
  }
  lines.push("} as const;");
  lines.push("");

  // -------- PrefabView 类 --------
  const className = config.viewClassName;
  lines.push(`const { ccclass } = _decorator;`);
  lines.push("");
  lines.push(`@ccclass("${className}")`);
  lines.push(`export class ${className} extends Component {`);

  // 字段
  for (const entry of config.nodes) {
    if (entry.exposeNode !== false) {
      const cmt = entry.comment ? `  /** ${escapeComment(entry.comment)} */\n` : "";
      lines.push(`${cmt}  public readonly ${entry.field}!: Node;`);
    }
    for (const comp of entry.components ?? []) {
      const info = lookupComponentType(comp.rawType);
      if (!info) continue;
      const fieldName = comp.field ?? defaultCompFieldName(entry.field, info.tsName);
      const cmt = comp.comment ? `  /** ${escapeComment(comp.comment)} */\n` : "";
      lines.push(`${cmt}  public readonly ${fieldName}!: ${info.tsName};`);
    }
  }
  lines.push("");

  // bind 方法
  lines.push(
    "  /**",
    "   * 把运行时 prefab 实例化出的 root Node 绑定到本 View。",
    "   * - 路径在生成期固化，运行时不做字符串拼接；",
    `   * - 任意 path 找不到节点时，DEV 模式抛错，Release 仅 console.warn。`,
    "   */",
    "  public bind(root: Node): this {",
    "    const w = this as any;",
    `    w.__root__ = root;`
  );

  for (const entry of config.nodes) {
    const nodeExpr = nodeAccessExpression("root", entry.path);
    const safeNodeVar = `n_${entry.field}`;
    if (entry.path === "") {
      lines.push(`    const ${safeNodeVar} = root;`);
    } else {
      lines.push(`    const ${safeNodeVar} = ${nodeExpr};`);
      lines.push(
        `    if (!${safeNodeVar}) { _genbotMissing(${JSON.stringify(entry.path)}); }`
      );
    }
    if (entry.exposeNode !== false) {
      lines.push(`    w.${entry.field} = ${safeNodeVar};`);
    }
    for (const comp of entry.components ?? []) {
      const info = lookupComponentType(comp.rawType);
      if (!info) continue;
      const fieldName = comp.field ?? defaultCompFieldName(entry.field, info.tsName);
      const idx = comp.index ?? 0;
      if (idx === 0) {
        lines.push(
          `    w.${fieldName} = ${safeNodeVar}?.getComponent(${info.tsName});`
        );
      } else {
        lines.push(
          `    {`,
          `      const _all = ${safeNodeVar}?.getComponents(${info.tsName}) ?? [];`,
          `      w.${fieldName} = _all[${idx}];`,
          `    }`
        );
      }
      lines.push(
        `    if (!w.${fieldName}) { _genbotMissing(${JSON.stringify(
          entry.path + "::" + info.tsName + (idx > 0 ? `#${idx}` : "")
        )}); }`
      );
    }
  }
  lines.push("    return this;", "  }");

  lines.push("}");
  lines.push("");

  // 公共 helper：缺失警告（一处定义，便于热点 patch）
  lines.push(
    "function _genbotMissing(what: string): void {",
    "  // DEV 模式下抛错，便于早暴；Release 下只警告，避免影响线上",
    "  // eslint-disable-next-line no-undef",
    `  const isDev = (typeof globalThis !== "undefined") && ((globalThis as any).CC_DEV || (globalThis as any).DEBUG);`,
    "  const msg = `[genbot] missing binding: ${what}`;",
    "  if (isDev) { throw new Error(msg); }",
    "  // eslint-disable-next-line no-console",
    "  console.warn(msg);",
    "}",
    ""
  );

  // 同名 prefab/path 数据元信息（可选，便于工具反查）
  lines.push(
    "export const __genbot_meta__ = {",
    `  prefab: ${JSON.stringify(config.prefab)},`,
    `  prefabName: ${JSON.stringify(config.prefabName)},`,
    `  totalNodes: ${parsed.stats.totalNodes},`,
    `  totalComponents: ${parsed.stats.totalComponents},`,
    `  exportedNodeCount: ${config.nodes.length},`,
    "} as const;",
    ""
  );

  return lines.join("\n");
}

function escapeComment(s: string): string {
  return s.replace(/\*\//g, "*\\/").replace(/[\r\n]+/g, " ");
}

function defaultCompFieldName(nodeField: string, tsName: string): string {
  const sanitized = tsName.replace(/[^A-Za-z0-9_]/g, "_");
  return `${nodeField}_${sanitized}`;
}

/**
 * 生成访问节点的链式表达式：
 *   "" → root
 *   "a" → root.getChildByPath("a")     // 单段也可以直接 getChildByName，但用 getChildByPath 更稳
 *   "a/b/c" → root.getChildByPath("a/b/c")
 *
 * 这里只用 getChildByPath，避免拼接错带来歧义；同名兄弟通过 bind.json 用 (1)/(2) 区分时，
 * 实际运行时仍依赖 getChildByPath，因此我们这里用 cocos 不直接支持的 (N) 语法时
 * 退化为索引访问（todo: v0.2 处理同名兄弟）。
 */
function nodeAccessExpression(rootVar: string, path: string): string {
  if (!path) return rootVar;

  // 简单情况：path 不含 "(" 同名兄弟修饰 → 直接 getChildByPath
  if (!/\(\d+\)/.test(path)) {
    return `${rootVar}.getChildByPath(${JSON.stringify(path)})`;
  }

  // 同名兄弟：path 段如 "name(2)"。逐段用 children[索引] 访问。
  const segs = path.split("/").map((seg) => {
    const m = /^(.*)\((\d+)\)$/.exec(seg);
    if (!m) return { name: seg, index: 0 };
    return { name: m[1], index: parseInt(m[2], 10) };
  });

  const tmps: string[] = [];
  let cursor = rootVar;
  for (let i = 0; i < segs.length; i++) {
    const s = segs[i];
    const next = `n${i}`;
    tmps.push(
      `(() => { const _ch = ${cursor}.children.filter(n => n.name === ${JSON.stringify(
        s.name
      )}); return _ch[${s.index}]; })()`
    );
    cursor = next;
  }

  // 把 IIFE 链合成单个表达式。为了简单这里直接嵌套：
  let expr = `${rootVar}`;
  for (const s of segs) {
    expr = `((__p) => __p ? __p.children.filter(n => n.name === ${JSON.stringify(
      s.name
    )})[${s.index}] : undefined)(${expr})`;
  }
  return expr;
}
